(()=>{const C=!!document.querySelector('script[type="importmap"]'),p=matchMedia("(display-mode: fullscreen), (display-mode: standalone), (display-mode: minimal-ui)").matches||navigator.standalone===!0,y=/iPhone|iPad|iPod/.test(navigator.userAgent)||navigator.platform==="MacIntel"&&navigator.maxTouchPoints>1&&!/Chrome\//.test(navigator.userAgent),W=matchMedia("(pointer: coarse)").matches,c=e=>document.querySelector(e),A=e=>{try{return localStorage.getItem(e)}catch{return null}},P=e=>{try{localStorage.setItem(e,String(Date.now()))}catch{}},m=e=>{const t=document.createElement("template");return t.innerHTML=e.trim(),t.content.firstElementChild};let o=null;function k(e,t,a,r,q){d();const l=m(`<div class="tc-bandeau" role="status" aria-live="polite" data-type="${e}">
      <div class="tc-t"><div class="tc-sur">${t}</div><div class="tc-txt">${a}</div></div>
      <div class="tc-b"><button class="tc-ok" type="button">${r}</button><button class="tc-non" type="button">Plus tard</button></div></div>`);l.querySelector(".tc-ok").onclick=()=>{d(),q()},l.querySelector(".tc-non").onclick=d,document.body.append(l),o=l,requestAnimationFrame(()=>requestAnimationFrame(()=>l.classList.add("vis")))}function d(){const e=o;o=null,e&&(e.classList.remove("vis"),setTimeout(()=>e.remove(),400))}let s=null;const g=()=>!p&&(!!s||y);addEventListener("beforeinstallprompt",e=>{e.preventDefault(),s=e,u()}),addEventListener("appinstalled",()=>{s=null,u(),o&&o.dataset.type==="invitation"&&d()});function h(){if(s){const e=s;s=null,u(),e.prompt()}else y&&E()}const f=m(`<div class="tc-installer" hidden>
    <button class="btn large" type="button">Installer l\u2019application</button>
    <p class="note">Sur l\u2019\xE9cran d\u2019accueil, en plein \xE9cran, consultable hors connexion.</p></div>`);f.querySelector("button").onclick=()=>{c("#m-partager")?.classList.remove("vis"),h()},c("#m-partager .boite")?.append(f);function u(){f.hidden=!g()}u();const L=e=>`<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${e}</svg>`;let i=null;function E(){i||(i=m(`<div class="modal" id="m-installer" role="dialog" aria-modal="true" aria-labelledby="tc-titre"><div class="boite">
        <div class="haut"><h2 id="tc-titre">Installer l\u2019application</h2><button class="fermer" type="button">Fermer</button></div>
        <p class="intro">Ajoutez la maquette \xE0 l\u2019\xE9cran d\u2019accueil&nbsp;: elle s\u2019ouvrira en plein \xE9cran, comme une application, et restera consultable hors connexion.</p>
        <ol class="tc-etapes">
          <li><span class="tc-pic">${L('<path d="M8.5 9.5H6v11h12v-11h-2.5"/><path d="M12 15V3.5M8.5 7 12 3.5 15.5 7"/>')}</span>
            <span>Touchez <b>Partager</b> dans Safari (sur iOS&nbsp;26, dans le menu \xAB&nbsp;\xB7\xB7\xB7&nbsp;\xBB).</span></li>
          <li><span class="tc-pic">${L('<path d="M4.5 4.5h15v15h-15z"/><path d="M12 8.5v7M8.5 12h7"/>')}</span>
            <span>Choisissez <b>Sur l\u2019\xE9cran d\u2019accueil</b>, en faisant d\xE9filer la liste si besoin.</span></li>
          <li><span class="tc-pic tc-mot">Ajouter</span>
            <span>Validez&nbsp;: l\u2019ic\xF4ne Tour Commune rejoint vos applications.</span></li>
        </ol></div></div>`),i.addEventListener("click",e=>{(e.target===i||e.target.classList.contains("fermer"))&&i.classList.remove("vis")}),document.body.append(i)),i.classList.add("vis")}const w=()=>k("invitation","Tour Commune","Installer l\u2019application","Installer",h);if(!p&&W&&!A("tc-invitation")){let e=0,t=!1;addEventListener("pointerdown",()=>{t=!0},{capture:!0,once:!0});const a=setInterval(()=>{const r=c("#charge");!t||document.hidden||o||c(".modal.vis")||r&&!r.classList.contains("fini")||(e++,!(e<30||!g()&&e<90)&&(clearInterval(a),g()&&(P("tc-invitation"),w())))},1e3)}let n=null;if(location.hostname==="localhost"&&(window.TC_APP={aideIOS:E,inviter:w,installer:h,registration:()=>n}),!("serviceWorker"in navigator))return;if(C){navigator.serviceWorker.getRegistrations().then(e=>e.forEach(t=>t.unregister())).catch(()=>{}),window.caches&&caches.keys().then(e=>e.forEach(t=>t.startsWith("tour-commune-")&&caches.delete(t))).catch(()=>{});return}const S=!!navigator.serviceWorker.controller;let b=!1,v=!1;const I=(document.querySelector('script[src*="app."]')?.getAttribute("src").match(/app\.(\d+)\.js/)||[])[1];navigator.serviceWorker.addEventListener("message",e=>{v||!e.data||!e.data.version||!I||e.data.version===I||(v=!0,location.reload())}),navigator.serviceWorker.addEventListener("controllerchange",()=>{if(!(v||!(b||S))){if(b)return v=!0,void location.reload();navigator.serviceWorker.controller?.postMessage("version")}});function M(){!n||!n.waiting||!navigator.serviceWorker.controller||k("maj","Tour Commune","Nouvelle version","Recharger",()=>{b=!0,n.waiting?n.waiting.postMessage("activer"):location.reload()})}async function j(){if(navigator.serviceWorker.controller&&!await navigator.serviceWorker.getRegistration())return;n=await navigator.serviceWorker.register("sw.js");const e=a=>a&&a.addEventListener("statechange",()=>{a.state==="installed"&&M()});M(),e(n.installing),n.addEventListener("updatefound",()=>e(n.installing));let t=Date.now();document.addEventListener("visibilitychange",()=>{document.hidden||Date.now()-t<30*6e4||(t=Date.now(),n.update().catch(()=>{}))}),p&&navigator.storage&&navigator.storage.persist&&navigator.storage.persist().catch(()=>{})}const T=()=>{const e=()=>j().catch(r=>console.info("service worker indisponible :",r.message));if(S)return e();let t=0;const a=setInterval(()=>{const r=c("#charge");r&&!r.classList.contains("fini")&&++t<40||(clearInterval(a),setTimeout(e,2e3))},500)};document.readyState==="complete"?T():addEventListener("load",T)})();
