(()=>{const M=!!document.querySelector('script[type="importmap"]'),v=matchMedia("(display-mode: fullscreen), (display-mode: standalone), (display-mode: minimal-ui)").matches||navigator.standalone===!0,f=/iPhone|iPad|iPod/.test(navigator.userAgent)||navigator.platform==="MacIntel"&&navigator.maxTouchPoints>1&&!/Chrome\//.test(navigator.userAgent),C=matchMedia("(pointer: coarse)").matches,c=e=>document.querySelector(e),A=e=>{try{return localStorage.getItem(e)}catch{return null}},P=e=>{try{localStorage.setItem(e,String(Date.now()))}catch{}},p=e=>{const t=document.createElement("template");return t.innerHTML=e.trim(),t.content.firstElementChild};let o=null;function b(e,t,a,i,j){d();const l=p(`<div class="tc-bandeau" role="status" aria-live="polite" data-type="${e}">
      <div class="tc-t"><div class="tc-sur">${t}</div><div class="tc-txt">${a}</div></div>
      <div class="tc-b"><button class="tc-ok" type="button">${i}</button><button class="tc-non" type="button">Plus tard</button></div></div>`);l.querySelector(".tc-ok").onclick=()=>{d(),j()},l.querySelector(".tc-non").onclick=d,document.body.append(l),o=l,requestAnimationFrame(()=>requestAnimationFrame(()=>l.classList.add("vis")))}function d(){const e=o;o=null,e&&(e.classList.remove("vis"),setTimeout(()=>e.remove(),400))}let s=null;const m=()=>!v&&(!!s||f);addEventListener("beforeinstallprompt",e=>{e.preventDefault(),s=e,u()}),addEventListener("appinstalled",()=>{s=null,u(),o&&o.dataset.type==="invitation"&&d()});function g(){if(s){const e=s;s=null,u(),e.prompt()}else f&&L()}const h=p(`<div class="tc-installer" hidden>
    <button class="btn large" type="button">Installer l\u2019application</button>
    <p class="note">Sur l\u2019\xE9cran d\u2019accueil, en plein \xE9cran, consultable hors connexion.</p></div>`);h.querySelector("button").onclick=()=>{c("#m-partager")?.classList.remove("vis"),g()},c("#m-partager .boite")?.append(h);function u(){h.hidden=!m()}u();const y=e=>`<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${e}</svg>`;let r=null;function L(){r||(r=p(`<div class="modal" id="m-installer" role="dialog" aria-modal="true" aria-labelledby="tc-titre"><div class="boite">
        <div class="haut"><h2 id="tc-titre">Installer l\u2019application</h2><button class="fermer" type="button">Fermer</button></div>
        <p class="intro">Ajoutez la maquette \xE0 l\u2019\xE9cran d\u2019accueil&nbsp;: elle s\u2019ouvrira en plein \xE9cran, comme une application, et restera consultable hors connexion.</p>
        <ol class="tc-etapes">
          <li><span class="tc-pic">${y('<path d="M8.5 9.5H6v11h12v-11h-2.5"/><path d="M12 15V3.5M8.5 7 12 3.5 15.5 7"/>')}</span>
            <span>Touchez <b>Partager</b> dans Safari (sur iOS&nbsp;26, dans le menu \xAB&nbsp;\xB7\xB7\xB7&nbsp;\xBB).</span></li>
          <li><span class="tc-pic">${y('<path d="M4.5 4.5h15v15h-15z"/><path d="M12 8.5v7M8.5 12h7"/>')}</span>
            <span>Choisissez <b>Sur l\u2019\xE9cran d\u2019accueil</b>, en faisant d\xE9filer la liste si besoin.</span></li>
          <li><span class="tc-pic tc-mot">Ajouter</span>
            <span>Validez&nbsp;: l\u2019ic\xF4ne Tour Commune rejoint vos applications.</span></li>
        </ol></div></div>`),r.addEventListener("click",e=>{(e.target===r||e.target.classList.contains("fermer"))&&r.classList.remove("vis")}),document.body.append(r)),r.classList.add("vis")}const k=()=>b("invitation","Tour Commune","Installer l\u2019application","Installer",g);if(!v&&C&&!A("tc-invitation")){let e=0,t=!1;addEventListener("pointerdown",()=>{t=!0},{capture:!0,once:!0});const a=setInterval(()=>{const i=c("#charge");!t||document.hidden||o||c(".modal.vis")||i&&!i.classList.contains("fini")||(e++,!(e<30||!m()&&e<90)&&(clearInterval(a),m()&&(P("tc-invitation"),k())))},1e3)}let n=null;if(location.hostname==="localhost"&&(window.TC_APP={aideIOS:L,inviter:k,installer:g,registration:()=>n}),!("serviceWorker"in navigator))return;if(M){navigator.serviceWorker.getRegistrations().then(e=>e.forEach(t=>t.unregister())).catch(()=>{}),window.caches&&caches.keys().then(e=>e.forEach(t=>t.startsWith("tour-commune-")&&caches.delete(t))).catch(()=>{});return}const w=!!navigator.serviceWorker.controller;let E=!1,I=!1;navigator.serviceWorker.addEventListener("controllerchange",()=>{I||!(E||w)||(I=!0,location.reload())});function S(){!n||!n.waiting||!navigator.serviceWorker.controller||b("maj","Tour Commune","Nouvelle version","Recharger",()=>{E=!0,n.waiting?n.waiting.postMessage("activer"):location.reload()})}async function W(){if(navigator.serviceWorker.controller&&!await navigator.serviceWorker.getRegistration())return;n=await navigator.serviceWorker.register("sw.js");const e=a=>a&&a.addEventListener("statechange",()=>{a.state==="installed"&&S()});S(),e(n.installing),n.addEventListener("updatefound",()=>e(n.installing));let t=Date.now();document.addEventListener("visibilitychange",()=>{document.hidden||Date.now()-t<30*6e4||(t=Date.now(),n.update().catch(()=>{}))}),v&&navigator.storage&&navigator.storage.persist&&navigator.storage.persist().catch(()=>{})}const T=()=>{const e=()=>W().catch(i=>console.info("service worker indisponible :",i.message));if(w)return e();let t=0;const a=setInterval(()=>{const i=c("#charge");i&&!i.classList.contains("fini")&&++t<40||(clearInterval(a),setTimeout(e,2e3))},500)};document.readyState==="complete"?T():addEventListener("load",T)})();
